export const PolicyActionConstants = {

    GET_POLICY_PAGINATED: "GET_POLICY_PAGINATED",
    GET_POLICY_PAGINATED_SUCCESS: "GET_POLICY_PAGINATED_SUCCESS",
    GET_METADATA: "GET_METADATA",
    GET_METADATA_SUCCESS: "GET_METADATA_SUCCESS",
}

export const AnalyticsActionConstants = {
    GET_DASHBOARD_STATS_SUCCESS: "GET_DASHBOARD_STATS_SUCCESS"
}